"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['data.json','myFunctions.py', 'no_pics.png']
#OPTIONS = {["os", "platform", "tkinter", "PIL", "json","pathlib","io", "turtle","textwrap"]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options=dict(py2app=dict(
        includes=["os", "platform", "tkinter", "PIL", "json","pathlib","io", "turtle","textwrap","random"]
    )),
    setup_requires=['py2app'],
)
